ALTER TABLE users ADD COLUMN IF NOT EXISTS club_name TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS region TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS organizer_note TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS skill_level TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_times TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS play_style TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;
